id: I503ED0D0
legacy_id: P004240
ocr_import_info:
  bdrc_scan_id: W19809
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T18:43:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:39:23.202715+00:00'
last_modified: 2022-08-30 23:39:44.141705
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19809
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW19809
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྷོ་འབྲུག་ཆོས་འབྱུང་།
  author: འབྲུག་རྗེ་མཁན་པོ ༦༩་དགེ་འདུན་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.6816207096119905
  ocr_word_median_confidence_index: 0.7400000095367432
quality: null
bases:
  I1KG3661:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3661
      total_pages: 386
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3661.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6816207096119905
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
